version: '2'

services:
    web:
        image: sofiannagounine/docker_web_flask
        #image: my_web_flask
        container_name: web_flask
        build:
            context: /home/stagiaire7/PycharmProjects/docker_web_server_flask/
        ports:
            -   "5000:5000"
        #network_mode: "host"
        #command:["-h=0.0.0.0"]
    jmeter:
        image: sofiannagounine/docker-jmeter
        #image: my_jmeter
        container_name: jmeter_web_flask
        build:
            context: /home/stagiaire7/dev-docker/docker/jmeter/
        volumes:
            - ./results:/results
        #command: ["-H", "web", "-P", "5000"]
        #links:
            #- web
    jenkins:
        image: jenkins:alpine
        hostname: localhost
        environment:
          JAVA_OPTS:   -Djava.util.logging.config.file=/var/jenkins_home
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
        - /home/stagiaire7/data:/var/jenkins_home
